kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - git clone https://github.com/muxueqz/kun.git

- name: build
  image: nimlang/nim
  commands:
  - nimble install -y nwt markdown
  - cd kun
  - nim c -d:release build.nim
