---
kind: pipeline
name: default

clone:
  # depth: 1
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  # 下载静态博客构建代码
  - git clone --depth=1 https://github.com/muxueqz/kun.git
  # 下载代码
  - git clone --depth=1 https://github.com/muxueqz/muxueqz-blog.git

- name: configure
  image: appropriate/curl
  commands:
  - cd kun
  - kun_latest=$(curl 'https://api.github.com/repos/muxueqz/kun/releases/latest' | grep -o '"browser_download_url":[ ]*"[^"]*' | cut -d'"' -f4)
  - echo $kun_latest
  - curl -L -o build $kun_latest

- name: build
  image: ubuntu
  commands:
  # 编译静态博客构建工具
  # - nimble install -y nwt markdown
  - cd kun
  # - nim c -d:release build.nim
  - rm -rf srcs
  - mv -v ../muxueqz-blog/ srcs
  - mkdir -pv public/tags/
  # 构建静态页面
  - chmod +x build
  - ./build

# 通过git push部署到git仓库，我用的是国内的coding.net
- name: git_push
  image: muxueqz/drone-git-push-by-bash
  settings:
    branch: master
    remote: git@e.coding.net:muxueqz/muxueqz.git
    force: true
    commit: true
    path: ./kun/public
    ssh_key:
      from_secret: GIT_PUSH_SSH_KEY
