---
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - git clone https://github.com/muxueqz/kun.git
  - git clone https://github.com/muxueqz/muxueqz-blog.git

- name: build
  image: nimlang/nim
  commands:
  - nimble install -y nwt markdown
  - cd kun
  - nim c -d:release build.nim
  - rm -rf srcs
  - mv -v ../muxueqz-blog/ srcs
  - mkdir -pv public/tags/
  - ./build

- name: git_push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@git.coding.net:muxueqz/muxueqz.git
    force: true
    commit: true
    path: ./kun/public
    key: 
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEA012PxDzbZL5o0MBnByDgK4dZgouo1tJeKLTCEEauAlY1J/ChODg7
      Hh0Wuu7/8GW+7uPGadRUIRhZIu+X8wV0Mza2ktuMNyfry4APQaDs3XVyGnoLAw3Kp/m0p7
      j+oZYL/0rVpfXplbGG9arcYr3gbh1uoCr3ePDMzJPOEXxi/MuMQ5QXeRQRhtE1qc4z22sE
      Zp5sj4GZVXDvaOEtpuGtsBUvDEldi/JF1YFsIQja7jFyPt1KTPu7dlLwGRF7PLvqL6f91o
      tfDLNrgs60+2ElBiJgAIEzjiKGRlNn2BdaTrwbw0PxH47lIdyHg/ZaqGqLMm+CRyLvQN30
      oRzRxYVMv6tHI9lDRbYHaSJFGYvJ1BUA+0awVV4lWLaCgKrFtBPg8KZdyib9CJYPhTMpud
      uq4Pc8Ex+8pjLzy8vdqGiGJRqYpWuB1YV/7KtHW9DUF8xSkbBfTRTfIqcgIFtkbRpREJSc
      yQtftNCwU/ViKvP/ElX9m1WAlj6Wv62eYR4J3LVZAAAFkFNxMpNTcTKTAAAAB3NzaC1yc2
      EAAAGBANNdj8Q822S+aNDAZwcg4CuHWYKLqNbSXii0whBGrgJWNSfwoTg4Ox4dFrru//Bl
      vu7jxmnUVCEYWSLvl/MFdDM2tpLbjDcn68uAD0Gg7N11chp6CwMNyqf5tKe4/qGWC/9K1a
      X16ZWxhvWq3GK94G4dbqAq93jwzMyTzhF8YvzLjEOUF3kUEYbRNanOM9trBGaebI+BmVVw
      72jhLabhrbAVLwxJXYvyRdWBbCEI2u4xcj7dSkz7u3ZS8BkRezy76i+n/daLXwyza4LOtP
      thJQYiYACBM44ihkZTZ9gXWk68G8ND8R+O5SHch4P2WqhqizJvgkci70Dd9KEc0cWFTL+r
      RyPZQ0W2B2kiRRmLydQVAPtGsFVeJVi2goCqxbQT4PCmXcom/QiWD4UzKbnbquD3PBMfvK
      Yy88vL3ahohiUamKVrgdWFf+yrR1vQ1BfMUpGwX00U3yKnICBbZG0aURCUnMkLX7TQsFP1
      Yirz/xJV/ZtVgJY+lr+tnmEeCdy1WQAAAAMBAAEAAAGBAI5BDh15B//J1ymIFM9LZRRmx+
      uAq2XJt+2Vmnbx2vNfqe7zmM4JqmAeG8o8SK03DUYirstTSDvt8y/8KTw6k3ZUgJRehwQo
      Lh6MVbhJ4qE6Bk2jjf3ELnzXJqsratS9890iNKC53TgOf1KgaCtct8vkqyvJPz16c5vMbo
      h+OvEA3aot5Y5r30/pRkC+s1AdupyGS3JaOySyGa9wvhTvFsLHvx550if6Kt4DeQ7SsuZV
      CRsePH+LfSOptkZo6ZR6s20lrsIb/Mrhdb5eqkII6xC5k9wufUWOjTfMiHeekOY/Dpj+TD
    OGURf93FunJTGODUSh60sC0VCjNSP+JnMOyurA3JJRS1PIAkJ0hDiiylX9elaAedZPRWET
    lWiInTZkBSWdwiO6uhM1QG62i4i3y/Ywyi3NDf1rK1E5aX6YMMDw0lUacBSUdqCAw53dXf
    zx/uyi7XhvtbguzDXFUWLlu34D3ZLlzZiWbtry7WWdIoK2Wu+yJ7X9HY7YTRmTGxrdcQAA
    AMEAxAS8ON1tIcYsYiZsoB1fBa8+dHfF9vFyIWW6mqoyFigzQJtOx4TUhZFha+h28p1CDS
    HoMg/G4+r3ZVuAx/MgxdaO8+b1tJ2woMGeICjYODDHqyIQ0GExtf+DwRWyJnBK1bgW3jXL
    JypL+96fCKCCB4nWLxMNbqNwezBX2PJEMOZHgAhLlGnZaRO01/j6Gg6O9fGGCEEeO/iiew
    Jl1049i9Kkmai3tB0ZmxDcY10WTlXGFsCRhQ7rPijnU8PhTRGJAAAAwQD3NF6J7k82QL73
    jYUqMruAif/cagxYdqboaY76Bi9zfIfqeY0tV7EskJClHj3DcwvBjVA0LSA73ANxwhJNGJ
    BewZmW4U6HMCm3XAyXjBtGtke3xGtrJbfr53xMwDAHuSAN4W0BMN3VgeW3Aes7/s0o3Apo
    crA3MZ2PWYDc35j7sXYgIJGt9wokhblIWNaFvJgtWYAVBi9JUz2Q3zDQX5aZPLKOxwDhnq
    AT4GRgMYkgtNI6JkOMvePBuMrCIzkPQKcAAADBANriwa7Yu5I0LHDDWpOSTZtkHQ98BGLB
    416ZitakxSS/6MUNUIEGNtLT0iJnpqEcjpXTFSRQNXlKzlfBBbbYPIswoRC69W84xyM8mw
    FpmRiqYcOBD1z+HH4xErckqQp8uITGbYO6HzYlq4kD7+kflY2YBd3k9ArwSs/K9hC7MTlH
    9rmAHlYZ1Cvik63TERTh2sM8C6hYVoPv6m1lRPQAo+zXjrfkHXVzQasqdsQg4OBgEBzI3E
    XnwaojAMm3/y0Z/wAAABRtdXh1ZXF6QG11eHVlcXoteDIzMAECAwQF
    -----END OPENSSH PRIVATE KEY-----
    # key:
      # from_secret: GIT_PUSH_SSH_KEY
---
kind: signature
hmac: 4a89193111cfa90023e095f6e0751b702aa87fcc96c91cddedfd00c62ead208b

...
