os:
  - linux

language: minimal

services:
  - docker

before_install:
- docker pull nimlang/nim

env:
  - BRANCH=0.20.2

cache:
  directories:
    - "$HOME/.choosenim/toolchains/nim-0.20.2"

# install:
  # - export CHOOSENIM_CHOOSE_VERSION=$BRANCH
  # - |
      # curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      # sh init.sh -y

# before_script:
  # - export CHOOSENIM_NO_ANALYTICS=1
  # - export PATH=$HOME/.nimble/bin:$PATH

script:
  # - nimble install -y nwt
  # - nimble install -y markdown
  - git clone --depth=1 https://github.com/muxueqz/kun
  - rm -rf kun/srcs/*.md
  - cp -a ./*.md kun/srcs/
  # - nim c -r build.nim
  - docker run --rm -v `pwd`/kun:/usr/src/app -w /usr/src/app nimlang/nim /bin/sh -c "nimble install -y nwt markdown; nim c -r build.nim"
