name: Build

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: srcs

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: muxueqz/kun
          path: kun

      - name: Configure
        run: |
          ls -alht
          cd kun
          kun_latest=$(curl 'https://api.github.com/repos/muxueqz/kun/releases/latest' | grep -o '"browser_download_url":[ ]*"[^"]*' | cut -d'"' -f4)
          echo $kun_latest
          curl -L -o build $kun_latest

      - name: Build
        run: |
          cd kun
          rm -rf srcs
          mv -v ../srcs/ srcs
          mkdir -pv public/tags/
          chmod +x build
          ./build

      - name: Git Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: pages
          repository: muxueqz/muxueqz-blog
          force: false
          directory: ./kun/public
          github_token: ${{ secrets.GITHUB_TOKEN }}
